/**
 * Centralized Error Codes for the ST-Solutions Platform Backend.
 * Standardized across all domain modules to prevent hardcoded error identifiers.
 */
export const ERROR_CODES = {
  // Authentication Error Codes (AUTH_*)
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_MISSING_HEADER: "AUTH_MISSING_HEADER",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_DISABLED: "AUTH_ACCOUNT_DISABLED",

  // Authorization Error Codes (FORBIDDEN_*)
  FORBIDDEN_RESOURCE_ACCESS: "FORBIDDEN_RESOURCE_ACCESS",
  FORBIDDEN_ROLE_REQUIRED: "FORBIDDEN_ROLE_REQUIRED",
  FORBIDDEN_INSUFFICIENT_PRIVILEGES: "FORBIDDEN_INSUFFICIENT_PRIVILEGES",

  // User Domain Error Codes (USER_*)
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_STATUS_INVALID: "USER_STATUS_INVALID",

  // Role & Permission Error Codes (ROLE_*, PERMISSION_*)
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  ROLE_ALREADY_EXISTS: "ROLE_ALREADY_EXISTS",
  ROLE_PROTECTED_SYSTEM_ROLE: "ROLE_PROTECTED_SYSTEM_ROLE",
  PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",
  PERMISSION_ALREADY_EXISTS: "PERMISSION_ALREADY_EXISTS",
  PERMISSION_PROTECTED: "PERMISSION_PROTECTED",

  // Application & Onboarding Error Codes (APPLICATION_*, VERIFICATION_*, QUESTION_*)
  APPLICATION_NOT_FOUND: "APPLICATION_NOT_FOUND",
  APPLICATION_ALREADY_EXISTS: "APPLICATION_ALREADY_EXISTS",
  APPLICATION_INVALID_STATUS: "APPLICATION_INVALID_STATUS",
  APPLICATION_STATUS_TRANSITION_INVALID: "APPLICATION_STATUS_TRANSITION_INVALID",
  APPLICATION_NOT_APPROVED: "APPLICATION_NOT_APPROVED",
  APPLICATION_ALREADY_PROCESSED: "APPLICATION_ALREADY_PROCESSED",
  VERIFICATION_NOT_FOUND: "VERIFICATION_NOT_FOUND",
  QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
  // Member Domain Error Codes (MEMBER_*)
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  MEMBER_ALREADY_EXISTS: "MEMBER_ALREADY_EXISTS",
  MEMBER_STATUS_INVALID: "MEMBER_STATUS_INVALID",
  MEMBER_STATUS_TRANSITION_INVALID: "MEMBER_STATUS_TRANSITION_INVALID",
  MEMBER_UNAUTHORIZED: "MEMBER_UNAUTHORIZED",
  MEMBER_RANK_NOT_FOUND: "MEMBER_RANK_NOT_FOUND",
  MEMBER_PROFILE_NOT_FOUND: "MEMBER_PROFILE_NOT_FOUND",
  MEMBER_CANNOT_MODIFY_SELF: "MEMBER_CANNOT_MODIFY_SELF",

  // Client Domain Error Codes (CLIENT_*)
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  CLIENT_ALREADY_EXISTS: "CLIENT_ALREADY_EXISTS",

  // Project Domain Error Codes (PROJECT_*)
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_STATUS_INVALID: "PROJECT_STATUS_INVALID",

  // Validation Error Codes (VALIDATION_*)
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VALIDATION_INVALID_INPUT: "VALIDATION_INVALID_INPUT",
  VALIDATION_MISSING_REQUIRED_FIELDS: "VALIDATION_MISSING_REQUIRED_FIELDS",

  // Database Error Codes (DATABASE_*)
  DATABASE_QUERY_ERROR: "DATABASE_QUERY_ERROR",
  DATABASE_CONSTRAINT_VIOLATION: "DATABASE_CONSTRAINT_VIOLATION",
  DATABASE_RECORD_NOT_FOUND: "DATABASE_RECORD_NOT_FOUND",
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",

  // Business Error Codes (BUSINESS_*)
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
  CONFLICT_RECORD_EXISTS: "CONFLICT_RECORD_EXISTS",

  // System & Generic Error Codes (SYSTEM_*)
  SYSTEM_INTERNAL_ERROR: "SYSTEM_INTERNAL_ERROR",
  SYSTEM_NOT_FOUND: "SYSTEM_NOT_FOUND",
  SYSTEM_SERVICE_UNAVAILABLE: "SYSTEM_SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
