/**
 * Centralized Error Codes for the ST-Solutions Platform Backend.
 * Standardized across all domain modules to prevent hardcoded error identifiers.
 */
export const ERROR_CODES = {
  // Authentication Error Codes (AUTH_*)
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_MISSING_HEADER: "AUTH_MISSING_HEADER",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_ACCOUNT_DISABLED: "AUTH_ACCOUNT_DISABLED",

  // Authorization Error Codes (FORBIDDEN_*)
  FORBIDDEN_RESOURCE_ACCESS: "FORBIDDEN_RESOURCE_ACCESS",
  FORBIDDEN_ROLE_REQUIRED: "FORBIDDEN_ROLE_REQUIRED",
  FORBIDDEN_INSUFFICIENT_PRIVILEGES: "FORBIDDEN_INSUFFICIENT_PRIVILEGES",

  // User Domain Error Codes (USER_*)
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_STATUS_INVALID: "USER_STATUS_INVALID",

  // Role & Permission Error Codes (ROLE_*, PERMISSION_*)
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  ROLE_ALREADY_EXISTS: "ROLE_ALREADY_EXISTS",
  ROLE_PROTECTED_SYSTEM_ROLE: "ROLE_PROTECTED_SYSTEM_ROLE",
  PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",
  PERMISSION_ALREADY_EXISTS: "PERMISSION_ALREADY_EXISTS",
  PERMISSION_PROTECTED: "PERMISSION_PROTECTED",

  // Application & Onboarding Error Codes (APPLICATION_*, VERIFICATION_*, QUESTION_*)
  APPLICATION_NOT_FOUND: "APPLICATION_NOT_FOUND",
  APPLICATION_ALREADY_EXISTS: "APPLICATION_ALREADY_EXISTS",
  APPLICATION_INVALID_STATUS: "APPLICATION_INVALID_STATUS",
  APPLICATION_STATUS_TRANSITION_INVALID: "APPLICATION_STATUS_TRANSITION_INVALID",
  APPLICATION_NOT_APPROVED: "APPLICATION_NOT_APPROVED",
  APPLICATION_ALREADY_PROCESSED: "APPLICATION_ALREADY_PROCESSED",
  VERIFICATION_NOT_FOUND: "VERIFICATION_NOT_FOUND",
  QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
  // Member Domain Error Codes (MEMBER_*)
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  MEMBER_ALREADY_EXISTS: "MEMBER_ALREADY_EXISTS",
  MEMBER_STATUS_INVALID: "MEMBER_STATUS_INVALID",
  MEMBER_STATUS_TRANSITION_INVALID: "MEMBER_STATUS_TRANSITION_INVALID",
  MEMBER_UNAUTHORIZED: "MEMBER_UNAUTHORIZED",
  MEMBER_RANK_NOT_FOUND: "MEMBER_RANK_NOT_FOUND",
  MEMBER_PROFILE_NOT_FOUND: "MEMBER_PROFILE_NOT_FOUND",
  MEMBER_CANNOT_MODIFY_SELF: "MEMBER_CANNOT_MODIFY_SELF",

  // Client Domain Error Codes (CLIENT_*)
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  CLIENT_ALREADY_EXISTS: "CLIENT_ALREADY_EXISTS",
  CLIENT_STATUS_INVALID: "CLIENT_STATUS_INVALID",
  CLIENT_STATUS_TRANSITION_INVALID: "CLIENT_STATUS_TRANSITION_INVALID",
  CLIENT_UNAUTHORIZED: "CLIENT_UNAUTHORIZED",
  CLIENT_OWNER_NOT_FOUND: "CLIENT_OWNER_NOT_FOUND",
  CLIENT_OWNERSHIP_INVALID: "CLIENT_OWNERSHIP_INVALID",
  CLIENT_MEMBER_NOT_FOUND: "CLIENT_MEMBER_NOT_FOUND",

  // Project Domain Error Codes (PROJECT_*)
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_STATUS_INVALID: "PROJECT_STATUS_INVALID",
  PROJECT_STATUS_TRANSITION_INVALID: "PROJECT_STATUS_TRANSITION_INVALID",
  PROJECT_CLIENT_NOT_FOUND: "PROJECT_CLIENT_NOT_FOUND",
  PROJECT_MEMBER_NOT_FOUND: "PROJECT_MEMBER_NOT_FOUND",
  PROJECT_MANAGER_NOT_FOUND: "PROJECT_MANAGER_NOT_FOUND",
  PROJECT_UPDATE_NOT_FOUND: "PROJECT_UPDATE_NOT_FOUND",
  PROJECT_UNAUTHORIZED: "PROJECT_UNAUTHORIZED",

  // Payment Domain Error Codes (PAYMENT_*)
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_CLIENT_NOT_FOUND: "PAYMENT_CLIENT_NOT_FOUND",
  PAYMENT_PROJECT_NOT_FOUND: "PAYMENT_PROJECT_NOT_FOUND",
  PAYMENT_STATUS_INVALID: "PAYMENT_STATUS_INVALID",
  PAYMENT_STATUS_TRANSITION_INVALID: "PAYMENT_STATUS_TRANSITION_INVALID",
  PAYMENT_ALREADY_EXISTS: "PAYMENT_ALREADY_EXISTS",
  PAYMENT_UNAUTHORIZED: "PAYMENT_UNAUTHORIZED",

  // Client Request Domain Error Codes (CLIENT_REQUEST_*)
  CLIENT_REQUEST_NOT_FOUND: "CLIENT_REQUEST_NOT_FOUND",
  CLIENT_REQUEST_ALREADY_EXISTS: "CLIENT_REQUEST_ALREADY_EXISTS",
  CLIENT_REQUEST_STATUS_INVALID: "CLIENT_REQUEST_STATUS_INVALID",
  CLIENT_REQUEST_STATUS_TRANSITION_INVALID: "CLIENT_REQUEST_STATUS_TRANSITION_INVALID",
  CLIENT_REQUEST_ALREADY_CONVERTED: "CLIENT_REQUEST_ALREADY_CONVERTED",
  CLIENT_REQUEST_CLIENT_EXISTS: "CLIENT_REQUEST_CLIENT_EXISTS",
  CLIENT_REQUEST_UNAUTHORIZED: "CLIENT_REQUEST_UNAUTHORIZED",

  // System Settings Error Codes (SETTINGS_*)
  SETTINGS_NOT_FOUND: "SETTINGS_NOT_FOUND",
  SETTINGS_INVALID_KEY: "SETTINGS_INVALID_KEY",
  SETTINGS_INVALID_VALUE: "SETTINGS_INVALID_VALUE",
  SETTINGS_UNAUTHORIZED: "SETTINGS_UNAUTHORIZED",

  // Audit Error Codes (AUDIT_*)
  AUDIT_LOG_NOT_FOUND: "AUDIT_LOG_NOT_FOUND",
  AUDIT_LOG_CREATION_FAILED: "AUDIT_LOG_CREATION_FAILED",
  AUDIT_UNAUTHORIZED: "AUDIT_UNAUTHORIZED",

  // Notification Error Codes (NOTIFICATION_*)
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_UNAUTHORIZED: "NOTIFICATION_UNAUTHORIZED",
  NOTIFICATION_ALREADY_READ: "NOTIFICATION_ALREADY_READ",
  NOTIFICATION_PREFERENCE_INVALID: "NOTIFICATION_PREFERENCE_INVALID",
  NOTIFICATION_DELIVERY_FAILED: "NOTIFICATION_DELIVERY_FAILED",

  // Validation Error Codes (VALIDATION_*)
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VALIDATION_INVALID_INPUT: "VALIDATION_INVALID_INPUT",
  VALIDATION_MISSING_REQUIRED_FIELDS: "VALIDATION_MISSING_REQUIRED_FIELDS",

  // Database Error Codes (DATABASE_*)
  DATABASE_QUERY_ERROR: "DATABASE_QUERY_ERROR",
  DATABASE_CONSTRAINT_VIOLATION: "DATABASE_CONSTRAINT_VIOLATION",
  DATABASE_RECORD_NOT_FOUND: "DATABASE_RECORD_NOT_FOUND",
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",

  // Business Error Codes (BUSINESS_*)
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
  CONFLICT_RECORD_EXISTS: "CONFLICT_RECORD_EXISTS",

  // System & Generic Error Codes (SYSTEM_*)
  SYSTEM_INTERNAL_ERROR: "SYSTEM_INTERNAL_ERROR",
  SYSTEM_NOT_FOUND: "SYSTEM_NOT_FOUND",
  SYSTEM_SERVICE_UNAVAILABLE: "SYSTEM_SERVICE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
